### ISSUE TITLE
sync with nextcloud podcast app

### ISSUE THREAD

**Issue by jakobroehrl** [thrillfall/nextcloud-gpodder#1]
Nice app, thanks!
It would be awesome, if the podcast app https://apps.nextcloud.com/apps/podcast would show these synced podcast sources, too.

**Comment by thrillfall** [comment]
the podcast app developer is aware of this app and will look into integration
https://github.com/AntennaPod/AntennaPod/pull/5243#issuecomment-870419935

**Comment by thrillfall** [comment]
since this ain't something we can fix here i moved this to the discussion board: https://github.com/thrillfall/nextcloud-gpodder/discussions/23
