### ISSUE TITLE
sync fails - due to invalid 3.7.0. update?

### ISSUE THREAD

**Issue by Linkinsoldier** [thrillfall/nextcloud-gpodder#105]
Hi,

I had tried to update to 3.7.0. and afterwards could update to 3.7.1. thanks to CLI and the quick update provoded by you.

Unfortunately i now get this every time it tries to sync (at least once a day):
![edited_Screenshot_20221113_105332_Nova7](https://user-images.githubusercontent.com/24806068/201516318-29d0ac0e-c41d-4b46-9c61-6851663639e2.jpg)

I am not sure how i can provide more details. Please tell me and i will try to provide.

## Environment
Android version: 12
OS version: 4.14.113-25257816
AntennaPod version: 2.7.1
Model: SM-G970F
Device: beyond0
Product: beyond0lteeea

No crash report recorded

**Comment by thrillfall** [comment]
What is your nextcloud version, database type.
Does it sync at all?

**Comment by JonOfUs** [comment]
The notification screenshot you shared states that the error relates to a gpodder.net sync and not to a Nextcloud-Gpodder sync.
Is this just a bug of AntennaPod or do you currently sync from AntennaPod to gpodder.net?

**Comment by Linkinsoldier** [comment]
Sorry for the late response, but i have been to the NFL munich game yesterday:)

I found the issue: everything was correctly set in antennapod, but i think the app did get deactivated in nextcloud itself. I thought i did Re enable it after the problematic update, but i could reactivate it now and that fixed it. 

Could this be cought in antennapod and displayed differently (should i write an antennapod ticket?)?

**Comment by thrillfall** [comment]
> Sorry for the late response, but i have been to the NFL munich game yesterday:)
> 
> I found the issue: everything was correctly set in antennapod, but i think the app did get deactivated in nextcloud itself. I thought i did Re enable it after the problematic update, but i could reactivate it now and that fixed it.
> 
> Could this be cought in antennapod and displayed differently (should i write an antennapod ticket?)?

Good idea
