### ISSUE TITLE
404 Error with AntennaPod

### ISSUE THREAD

**Issue by jayboc** [thrillfall/nextcloud-gpodder#12]
Hi I run a self hosted Nextcloud on debian server from official snap repository. I installed GPodderApp from nextcloud store as admin.

I setup my HTTPS://URL.IRL on AntennaPod with login (secondary user) and app-password.

Antenna Pod return : Bas Response Code : 404

Thank you !

**Comment by thrillfall** [comment]
What do you mean by "setup my ...... on AntennaPod"?
You do use the single-sign-on via Nextcloud app, right? Where you select your preconfigured nc account and then grant access.

**Comment by jayboc** [comment]
I simply set URL, login and password in the setting windows of AntennaPod (Prefereences > Synchronisation > Identifier (with custom server)

**Comment by thrillfall** [comment]
The integration for the gpoddersync app was not merged to AntennaPod release code (yet). It is still a PR(https://github.com/AntennaPod/AntennaPod/pull/5243)
You can download a debug build and try that with your nc server. Find the link in the PR discussions
