### ISSUE TITLE
No episode changes synchronization when using MySQL

### ISSUE THREAD

**Issue by JonOfUs** [thrillfall/nextcloud-gpodder#13]
Episode changes cannot be inserted into MySQL DB. Instead, the table stays empty and they don't get synchronized.

## Expected Behavior
Episode changes should be inserted into oc_gpodder_episode_action table.

## Current Behavior
When using MySQL, episode changes are not inserted into the table.
The sql command produces an error: `ERROR 1292 (22007): Incorrect datetime value: 'Wed Jul 21 23:16:48 GMT+02:00 2021' for column nctest.oc_gpodder_episode_action.timestamp at row 1`.

## Possible Solution
Change Datetime format when using MySQL databases, because they do not support abstract datetimes like 'Wed Jul 21, GMT+02:00'.

## Steps to Reproduce

1. Activate MySQL general_log
2. Install gpoddersync app on Nextcloud, install AntennaPod debug, connect to nextcloud account, play/pause episodes
3. Find sql command in log that looks like:
  - `INSERT INTO 'oc_gpodder_episode_action' ('podcast', 'episode', 'action', 'position', 'started', 'total', 'timestamp', 'user_id') VALUES('https://example.com/feed.xml', 'https://example.com/episode.mp3', 'PLAY', '144', '141', '200', 'Wed Jul 21 23:16:48 GMT+02:00 2021', 'user');`
4. Run SQL command through MySQL CLI or phpmyadmin => an error is produced

## Context (Environment)
Using MariaDB 10.3, php8.0, Nextcloud 22, gpoddersync 1.0.7, Raspberry Pi OS 64bit, nginx 1.14.2

## Detailed Description
I am a bloody beginner, but reading documentation I think the problem is that MySQL does not support datetime strings like the given one. PostgreSQL does, though.

Looked into the code and I think the problem could be in EpisodeActionEntity.php: 
https://github.com/thrillfall/nextcloud-gpodder/blob/228be0b0b89aa85a1039e405c4ba0e3e519d061d/lib/Db/EpisodeAction/EpisodeActionEntity.php#L33
There the format for datetime is specifically defined, but in the SQL command is a completely different datetime format (Wed Jul 21 23:16:48 GMT+02:00 2021).

Could it therefore be an error in EpisodeActionEntity.php in the interaction between `jsonSerialize()` and the datetime setter from Entity.php? 
https://github.com/nextcloud/server/blob/769f84f31dafb4e0739d2a7b03242c53b66a896d/lib/public/AppFramework/Db/Entity.php#L119
![grafik](https://user-images.githubusercontent.com/11487762/126617436-1e220db0-8c4f-41a2-8600-54303e1babeb.png)

**Comment by thrillfall** [comment]
release 1.0.8 should fix it. @JonOfUs can you please update and verify?

**Comment by JonOfUs** [comment]
Installed 1.0.8 by cloning repository, because it was not yet available.

It seems to work :) I will test it a bit more later this day and will close the issue.
Thanks 😊

**Comment by JonOfUs** [comment]
Yes, it now works.

Sometimes, if I start an episode, skip chapters to e.g. minute 5:30 and then pause again it happens that the episode play state gets synchronized back to the playback position from before.

But this is no problem concerning MySQL, I will comment this into the pull request discussion in the AntennaPod repository.
