### ISSUE TITLE
Failed sync with antennaPod: "make sure the cursor is initialized correctly"

### ISSUE THREAD

**Issue by Koantig** [thrillfall/nextcloud-gpodder#136]
Hi there,

I've installed gpoddersync on my nextcloud and successfully synced my podcast data (from AntennaPod). After that, I removed gpoddersync as I was fiddling with something. I've re-installed it and since then I'm getting an error while syncing:
> gpodder.net sync error:
> couldn't read row 1023, col 0 from CursorWindow. Make sure the cursor is initialized correctly before accessing data from it.

I did notice that after re-installing gpoddersync, the app started off with some left-over data already. Could that be the issue? AntennaPod would have moved on since then.
I did try "Force full synchronization" but it didn't work either.

Thank you

**Comment by JonOfUs** [comment]
Hi,
it sounds like AntennaPod is showing this error message, right?
I am not sure what this error means, but if it is shown in AntennaPod, I think it could probably be a problem with the app itself. If possible, it would maybe be good to create an issue there, if you haven't already done this: https://github.com/AntennaPod/AntennaPod/issues

AntennaPod has a feature to export a more detailed log, under `Settings` > `Report bug` > the menu on the top right. Maybe there is something useful in there on what lead to this error.

**Comment by Koantig** [comment]
ah ok, thank you! I wasn't sure which side to ask, I ended up picking the wrong one :)
I'll ask AntennaPod.
