### ISSUE TITLE
AntennaPod seemingly receives 302 / HTML response, sync fails because response not JSON

### ISSUE THREAD

**Issue by FunctionDJ** [thrillfall/nextcloud-gpodder#137]
Here's what i see in the Nextcloud logs when i try to sync with AntennaPod:
```
192.168.96.15 - function [20/Jul/2023:18:53:10 +0000] "GET //index.php/apps/gpoddersync/subscriptions?since=0 HTTP/1.1" 302 883 "-" "AntennaPod/3.0.2"
192.168.96.15 - function [20/Jul/2023:18:53:10 +0000] "GET /apps/files/ HTTP/1.1" 200 9519 "-" "AntennaPod/3.0.2"
```
I would have expected the response to have code 200. Since it seems to redirect to the files page, it probably returns HTML and AntennaPod says synchronisation failed. I've inspected the AntennaPod logs and it's basically just the JSON parsing failing, which makes syncing fail.

I also noticed that the requested URL seems to have two forward slashes in front of the `index.php`. I made sure to set up the Nextcloud server URL with without a trailing slash. Could this be the reason for the redirect or is there something wrong with my setup? I'm using nginx-proxy-manager.

**Comment by FunctionDJ** [comment]
AntennaPod 3.0.2
GpodderSync 3.8.1 (manual install)
Nextcloud 24.0.7 (Docker) (yes, i should update at some point)

**Comment by JonOfUs** [comment]
Hi,
to my knowledge, the double slashes shouldn't be a problem. Is it maybe possible that the app gpoddersync is not correctly enabled inside Nextcloud? This would explain the redirect to `/apps/files`.

**Comment by thrillfall** [comment]
Unless you find the reason for the redirect to /files there is nothing beyond guessing we could help you with.

**Comment by FunctionDJ** [comment]
I'll check with an HTTP client (Insomnia) in a bit and report back.

**Comment by FunctionDJ** [comment]
I figured it out. Nextcloud disabled the app because my installation doesn't meat the version criteria. JonOfUs had the right idea. I'll look for an older version of the app that supports my NC installation.

**Comment by FunctionDJ** [comment]
It's working now ❤️
