### ISSUE TITLE
link on https://apps.nextcloud.com/apps/gpoddersync to `Ask questions or discuss` is dead

### ISSUE THREAD

**Issue by foss-** [thrillfall/nextcloud-gpodder#138]
https://apps.nextcloud.com/apps/gpoddersync has a link to `Ask questions or discuss` directing to https://help.nextcloud.com/c/apps/gpoddersync which loads `Oops! That page doesn’t exist or is private.`.

Since GitHub Discussions are used that link could maybe direct to https://github.com/thrillfall/nextcloud-gpodder/discussions?

<img width="913" alt="1" src="https://github.com/thrillfall/nextcloud-gpodder/assets/5708172/1f26ccb5-6355-4d80-9c25-58940ec86a4c">

**Comment by thrillfall** [comment]
Feel free to do the necessary change. I'll release it then
