### ISSUE TITLE
Installation fails: App with id gpoddersync has invalid signature

### ISSUE THREAD

**Issue by ovk** [thrillfall/nextcloud-gpodder#142]
An attempt to install this app fails with the following error:

```
An error occured during the request. Unable to proceed.
App with id gpoddersync has invalid signature
```

**Comment by JonOfUs** [comment]
Hmm, installing the app works without problems for me on NC27.
Which Nextcloud version are you using?
And could you try removing the app and then download&install again?

**Comment by ovk** [comment]
It's Nextcloud 24, which as I just realized technically no longer supported, so maybe it's not even a valid issue.
I will try to upgrade it and give it a try.

**Comment by ovk** [comment]
Upgraded to 26 and the installation succeeded.
Closing this issue since 24 is no longer supported anyway. Thanks!
