### ISSUE TITLE
Feature request: add minimal API documentation

### ISSUE THREAD

**Issue by mogwa1** [thrillfall/nextcloud-gpodder#16]
I'm currently looking into adding gpodder sync support into Kasts (KDE convergent podcast player).  It would be nice to also offer self-hosted options, especially if the API is (near) identical.

Assuming that your API is almost identical to gpodder's, could you please add some (minimal) documentation?  E.g. what's the base URL for making GET and POST requests?  What are the differences wrt gpodder.net API?  Etc.

Currently, people would have to dive into the source code to find out.

**Comment by thrillfall** [comment]
Yes. When the integration with antennapod is stable

**Comment by thrillfall** [comment]
please see the README for the very minimal API documentation
