### ISSUE TITLE
Parsing Error

### ISSUE THREAD

**Issue by rezeero25** [thrillfall/nextcloud-gpodder#162]
Using gpodder Sync 3.8.3 with Nextcloud 28.0.3 i get this parsing errors. I'm using AntennaPod 3.2.0 and tried a "forced synch".

```
SimpleXMLElement::__construct(): &lt;/div&gt; at /var/www/nextcloud/apps/gpoddersync/lib/Core/PodcastData/PodcastData.php#42 
```
```
SimpleXMLElement::__construct(): Entity: line 290: parser error : Opening and ending tag mismatch: br line 290 and p at /var/www/nextcloud/apps/gpoddersync/lib/Core/PodcastData/PodcastData.php#42 
```
```	
SimpleXMLElement::__construct(): ^ at /var/www/nextcloud/apps/gpoddersync/lib/Core/PodcastData/PodcastData.php
```
```
SimpleXMLElement::__construct(): Entity: line 312: parser error : Premature end of data in tag div line 171 at /var/www/nextcloud/apps/gpoddersync/lib/Core/PodcastData/PodcastData.php#42
```

These Errors happen, when i open the gpodder settings in nextcloud (https://[...]/nextcloud/settings/user/gpoddersync)

Help or hints in the right direction are much appreciated

**Comment by JonOfUs** [comment]
Hi, the error messages indicate that some of the podcasts you subscribed to use invalid XML syntax in their feed. You probably cannot do a lot about it, but it shouldn't affect the synchronisation.
How do the errors show up? Do they appear in the Nextcloud logs? And does the website still work as expected or does it malfunction if the errors occur?
