### ISSUE TITLE
GPodder not updated

### ISSUE THREAD

**Issue by skvaller** [thrillfall/nextcloud-gpodder#166]
Description on Nextcloud says I need a lower server version than 28?
It worked just fine until last NC update. 
![2024-04-04 09 36 27 op1 se a3e15644f498](https://github.com/thrillfall/nextcloud-gpodder/assets/37003762/0f64c1ec-bfe1-4b29-803e-b52095e73e39)

**Comment by JonOfUs** [comment]
This indicates that you are using Nextcloud 29 or later, but this app in its current version only supports Nextcloud 26, 27 and 28. The error messages says that you need a server version of at most 28.

**Comment by skvaller** [comment]
Thank you for the update on my issue, much appreciated.

**Comment by MaxXor** [comment]
@thrillfall Can you please release an update for NC 29?

**Comment by todi** [comment]
Using the current version with NC 29 i get a lot of the following errors in my logs:
`ReflectionException Class "OCA\GPodderSync\Controller\EpisodeActionController" does not exist`

**Comment by MrGhostlyOrb** [comment]
@Amolith How were you able to test on NC 29, I would also like to apply the update unofficially?

**Comment by JonOfUs** [comment]
Fixed with release 3.9.0: https://github.com/thrillfall/nextcloud-gpodder/releases/tag/3.9.0
