### ISSUE TITLE
Make GPodder Sync Nextcloud Hub 8 (v 29) compatible

### ISSUE THREAD

**Issue by brot** [thrillfall/nextcloud-gpodder#169]
Nextcloud Hub 8 (version > 29) just released and the GPodder Sync app is shown to be not compatible with this version.
Would be awesome if you could release a new and compatible version.
Thanks in advance!

**Comment by rhortal** [comment]
Do we know what the differences are? Good candidate for a PR but not really sure where to start

**Comment by smoothml** [comment]
I think #163 might resolve this.

**Comment by nunombispo** [comment]
When will this be updated?

I run a shared Nextcloud server and would like to update to v29 but cannot do so now, since GPodderSync is a very used app.

**Comment by JonOfUs** [comment]
New release is out, adding compability with Hub 8. Let us know if there are any problems with the new release.

**Comment by JonOfUs** [comment]
@metronidazole is this still the case? I fear I can't do any more, since it is published to the [official Nextcloud app store](https://apps.nextcloud.com/apps/gpoddersync). So if it still doesn't work, there's probably something wrong with your Nextcloud.

**Comment by benmordecai** [comment]
I am not @metronidazole but personally I am using Nextcloud 29 with the current GPodder Sync with no problems
