### ISSUE TITLE
Support NextCloud 30

### ISSUE THREAD

**Issue by ImranR98** [thrillfall/nextcloud-gpodder#178]
Hi, thanks for writing this great app!
Seems like it needs an update to work on the latest NextCloud version.

**Comment by fyksen** [comment]
Looks like it works with Nextcloud 30, you just need to force enable it.
Go into apps -> deactivated apps -> GPodder sync -> enable unsafe (or something, can't remember the wording).

**Comment by ImranR98** [comment]
You're right, that worked. Thanks!

**Comment by nogweii** [comment]
I think this should be re-opened, even though it's not broken it would still be better to not require force-activating the app.

**Comment by fyksen** [comment]
Created a PR in https://github.com/thrillfall/nextcloud-gpodder/pull/179
