### ISSUE TITLE
Sync from NC back to AntennaPod doesn't work.

### ISSUE THREAD

**Issue by tompomdg** [thrillfall/nextcloud-gpodder#182]
# APP Version

3.10.0

# What I've tried

Different AntennaPod Versions from 3.4.0 > 3.4.1 > 3.5

# Expected behaviour 

Clean installed AntennaPod should be synced with existing Nextcloud gpodder database.
All podcast subscription should be copied.

# Current behaviour

The first subscribed podcast is copied succesfully, all after that not.
If the first podcast allready exists, the second will be copied succesfully, all after that not .. and so on.
All not succesfully copied podcast are "unknown podcast"

![_Photos_Android_Screenshots_Screenshot_20241015-185820](https://github.com/user-attachments/assets/cd772930-516a-4533-848d-b1903bac4db9)

**Comment by thrillfall** [comment]
it will sync. give it some time. or reload the subscription list. then all other subscriptions will by synced

**Comment by tompomdg** [comment]
ty, it works.

**Comment by ByteHamster** [comment]
Starting with AntennaPod 3.6, this should become more reliable with the first sync already
