### ISSUE TITLE
Integrate with the Music application's Podcasts list

### ISSUE THREAD

**Issue by gbraad** [thrillfall/nextcloud-gpodder#183]
Is there a way to edit feeds from the Nextcloud interface?
If not, would be nice if the Music application can be modified to 'detect' (use) gpodder and provide a means to edit the feeds.

**Comment by JonOfUs** [comment]
Hi,

[RePod](https://apps.nextcloud.com/apps/repod) communicates with gpoddersync. You can listen to and also delete subscriptions with this app from inside your Nextcloud.
