### ISSUE TITLE
Update repository to v2.0.0

### ISSUE THREAD

**Issue by JonOfUs** [thrillfall/nextcloud-gpodder#28]
The repository seems to be out-of-date, since in the Nextcloud app store the app already reached v2.0.0.

Branch process-optional-guid needs to be merged into main. I haven't created a PR, because @thrillfall probably has a mergeable v2.0.0 branch? It seems like it just isn't uploaded yet, since v2.0.0 is online.

**Comment by thrillfall** [comment]
I pushed the tagged orphaned release commit to main. Do know how this happend. Thanks for pointing this out.
All changes are in main
