### ISSUE TITLE
Column "oc_gpodder_subscriptions"."subscribed" is type Bool and also NotNull

### ISSUE THREAD

**Issue by mattsches** [thrillfall/nextcloud-gpodder#3]
As mentioned [here](https://github.com/thrillfall/nextcloud-gpodder/issues/2#issuecomment-876172479) before by @arsenty, NC22+ (I'm on the latest master) throws an error when trying to enable the app:
```
Column "oc_gpodder_subscriptions"."subscribed" is type Bool and also NotNull, so it can not store "false".
```
This is due to some extra checks introduced in the `MigrationService`, it seems.
A solution could be:
```
$table->addColumn('subscribed', Types::BOOLEAN, [
	'notnull' => false,
]);
```

**Comment by thrillfall** [comment]
Thank you. I put your fix in release 1.0.4 and now the app also supports nextcloud version 22 :muscle: 

May i ask what you do with the app? Is there a client that can use this?

**Comment by mattsches** [comment]
Great, thank you 🙂

I'm planning to use the app to sync my podcasts from AntennaPod. I've been thinking for a while that someone should build a clone of the Gpodder API for self-hosting. Although I'm a long-time Nextcloud user, it didn't occurr to me that NC would be a perfect place for this.

I cannot promise anything, but if I find the time I will try to contribute to this app. Keep up the great work! I hope the AntennaPod devs will merge your PR :crossed_fingers:

**Comment by thrillfall** [comment]
> Great, thank you 🙂
> 
> I'm planning to use the app to sync my podcasts from AntennaPod. I've been thinking for a while that someone should build a clone of the Gpodder API for self-hosting. Although I'm a long-time Nextcloud user, it didn't occurr to me that NC would be a perfect place for this.
> 
> I cannot promise anything, but if I find the time I will try to contribute to this app. Keep up the great work! I hope the AntennaPod devs will merge your PR 🤞

Nice to hear from future users ;-)
