### ISSUE TITLE
Download link broken

### ISSUE THREAD

**Issue by Seb3thehacker** [thrillfall/nextcloud-gpodder#36]
![error](https://user-images.githubusercontent.com/88462253/136446814-81a9beeb-6763-4644-bee7-5a155a224c04.png)

Nextcloud 21 with latest PHP installed and all necessary modules.

Error:
Client error: `GET https://github.com/thrillfall/nextcloud-gpodder/raw/main/releases/gpoddersync-1.0.4.tar.gz` resulted in a `404 Not Found` response: <!DOCTYPE html> <html lang="en" data-color-mode="auto" data-light-theme="light" data-dark-theme="dark"> <head> (truncated...)

**Comment by Seb3thehacker** [comment]
Ok thanks. To be clear, there are no plans to support Nextcloud < 20?

**Comment by thrillfall** [comment]
No. Since we raised the minimum php level to 7.4 nc < 20 is not possible anymore
