### ISSUE TITLE
Return server timestamp after uploading subscription changes

### ISSUE THREAD

**Issue by mogwa1** [thrillfall/nextcloud-gpodder#43]
I first want to say that I *love* your work on nextcloud-gpodder.  It's an enormous improvement over gpodder.net and it's absolutely trivial to set up self-hosting.

The gpodder API returns timestamps for all GET and POST actions on subscriptions and episode actions.
Nextcloud-gpodder is also returning server timestamps for all requests except `POST /index.php/apps/gpoddersync/subscription_change/create`

Could you also have nextcloud-gpodder return a server timestamp in order to be fully compatible with the gpodder API?

**Comment by thrillfall** [comment]
Next on the list when I or s.o. else has time. Thanks for pointing this out

**Comment by JonOfUs** [comment]
Done. Should be 3.0.2. Changelog message could be: 
```Markdown
## 3.0.2 - 2021-10-17
### Changed
- subscription upload now also responds with server timestamp
```
