### ISSUE TITLE
Auto skip at end of episode does not mark as played

### ISSUE THREAD

**Issue by Froghut** [thrillfall/nextcloud-gpodder#46]
As the title says if you auto skip some time at the end of episodes they won't get marked as played and when synchronizing on another device are shown as not played but played until close to the end.
I realize this should probably be fixed in AntennaPod, but since you also created the PR for the nextcloud gpodder AntennaPod stuff I thought I'd post this here.

**Comment by thrillfall** [comment]
You realized correctly that nothing can be done in this repository to fix the issue. So please raise the issue in the responsible repository https://github.com/AntennaPod/AntennaPod
