### ISSUE TITLE
Question: What is the VersionController for?

### ISSUE THREAD

**Issue by mattsches** [thrillfall/nextcloud-gpodder#5]
Just out of interest: `VersionController` returns a hardcoded version `0.1` - is this supposed to be the version of the app, or the version of the API?

Will clients use it at some point to detect available features?

**Comment by thrillfall** [comment]
This was supposed to be a URL with which a client could verify that gpoddersync APP was even installed.
But that feature is still in development on client side

**Comment by mattsches** [comment]
Ok, thank you for the explanation 👍
