### ISSUE TITLE
How do I use this?

### ISSUE THREAD

**Issue by kongo09** [thrillfall/nextcloud-gpodder#53]
I have Nextcloud 23 running and installed this app. On Android, I have AntennaPod 2.4.1 from 28 Nov 2021.

When I select to sync with gpodder and choose another server, entering my Nextcloud details, I get the error
```
Value <!DOCTYPE of type java.lang.String cannot be converted to JSONArray
```
I'm sure, I miss something simple here?

**Comment by JonOfUs** [comment]
The synchronization with Nextcloud gpoddersync will be available in AntennaPod 2.5.0, which is not yet released. So you could install a debug version of AntennaPod which contains the new feature (be warned that it could break some things) or wait for the official beta or the official release of 2.5.0. I don't know when 2.5.0 will be released, but it once was planned towards the end of 2021.

**Comment by kongo09** [comment]
Thanks for clarifying. I have added myself to the Android beta channel of AntennaPod, but so for no 2.5.0 version in sight. So I'll wait. 

Merry Christmas! 🎄

**Comment by thrillfall** [comment]
Yes, it is very weird. Antennapod has a release cycle like they still develop decades ago. 🤷

**Comment by 2br-2b** [comment]
I'm testing, and this works well in KDE's Kasts app
