### ISSUE TITLE
opml subscriptions file

### ISSUE THREAD

**Issue by edgartaor** [thrillfall/nextcloud-gpodder#54]
I'm trying to sync my podcast subscriptions into [gPodder](https://gpodder.github.io/) but apparently it expects an opml file from a url like `/subscriptions/username.opml` in the nextcloud server.

Is this not implemented in this app?

**Comment by JonOfUs** [comment]
Hi, no, it isn't. Since Nextcloud limits how api urls can look, synchronization with gpoddersync has to be implemented explicitly into any podcast app.

Supported apps are listed in the [Readme.md](https://github.com/thrillfall/nextcloud-gpodder#readme).
