### ISSUE TITLE
Signing into Kasts to Nextloud 23 fails

### ISSUE THREAD

**Issue by llucps** [thrillfall/nextcloud-gpodder#56]
I installed Kasts 22.02 (the latest) and Nextcloud 23.0.2 with Goppdersync 3.2 and I haven't been able to sign in. I'm getting this error looking at the Nextcloud logs:

```
[index] Error: Typed property OCA\GPodderSync\Controller\SubscriptionChangeController::$userId must be string, null used

GET /index.php/apps/gpoddersync/subscriptions?since=0
from xx.xxx.xx.xxx at 2022-03-20T10:27:20+01:00
```

It seems the SubscriptionChangeController class is expecting the $userId to be a string, which it is:

```
class SubscriptionChangeController extends Controller {

	private SubscriptionChangeSaver $subscriptionChangeSaver;
	private SubscriptionChangeRepository $subscriptionChangeRepository;
	private string $userId;

	public function __construct(
		string $AppName,
		IRequest $request,
		$UserId,
		SubscriptionChangeSaver $subscriptionChangeSaver,
		SubscriptionChangeRepository $subscriptionChangeRepository

	) {
		parent::__construct($AppName, $request);
		$this->subscriptionChangeSaver = $subscriptionChangeSaver;
		$this->subscriptionChangeRepository = $subscriptionChangeRepository;
		$this->userId = $UserId;
	}
```

![Screenshot 2022-03-20 at 10 38 03](https://user-images.githubusercontent.com/25823659/159156586-c620f380-dae0-48fb-930b-863154ecda2e.png)

Is this a known bug?
Thanks.

**Comment by llucps** [comment]
Nevermind my fault.. I had to creat a new app on nextcloud on the security settings.. and now it works.

Sorry.

**Comment by mattsches** [comment]
@llucps What exactly did you do? What do you mean by "create a new app on the security settings"?

I'm getting the same error and would like to fix it, too ;)

**Comment by JonOfUs** [comment]
An app password is necessary if 2FA is active in Nextcloud (only in Kasts since Antennapod uses the Login Flow).
Open Nextcloud user settings -> Security -> scroll down to the end of page -> insert app name (e.g. "KDE Kasts") -> create new App password. Then you can login in Kasts with your username and the provided app password.

Was that the problem or is it something else?

**Comment by mattsches** [comment]
Thanks, @JonOfUs I created an app password, and the error seems to be gone. However, Kasts still does not sync, but that might be an issue with Kasts.
