### ISSUE TITLE
The Login Process to a local Nextcloud Instance never gets done

### ISSUE THREAD

**Issue by Tommy-01** [thrillfall/nextcloud-gpodder#61]
Hi, i got a Problem with the login Process to my local Nextcloud Process.
I already posted it here --> 
[https://github.com/AntennaPod/AntennaPod/issues/5841](https://github.com/AntennaPod/AntennaPod/issues/5841)

Maybe this was the wrong place?
Could you help?
I realy would like to use this App.

Thank you!

**Comment by thrillfall** [comment]
This app does not deal with authentication to your nextcloud. The issue you raised at antennapod is the right place
