### ISSUE TITLE
provide changelogs

### ISSUE THREAD

**Issue by nrgeen** [thrillfall/nextcloud-gpodder#7]
Hey. Great idea and great work so far. 
Can you please provide changelogs for each new version?
For me as admin it is important to know what has changed in an update.
Again. Thanks for your work! 🚀

**Comment by thrillfall** [comment]
how exactly do you expect changelogs?

**Comment by nrgeen** [comment]
Hello. 
That is one possibility. 
I am basically concerned with functions, changes and optimisations.
I like the way it is handled in the repo of [nextcloud/calendar](https://github.com/nextcloud/calendar/blob/master/CHANGELOG.md). Here, a changelog.md has simply been created in which the changelog is documented. A subdivision into Added, Changed, Fixed would make things clearer. The way it is done also seems informative to me. Elsewhere, this is supplemented by the point Features.

Please understand it merely as a suggestion that makes it more comprehensible for me personally.
Thank you very much!

**Comment by thrillfall** [comment]
i'll document things now here: https://github.com/thrillfall/nextcloud-gpodder/blob/main/CHANGELOG.md

thanks for showing me how to!

**Comment by nrgeen** [comment]
With pleasure. I am very glad that I could support you.
