### ISSUE TITLE
Cant login. Trust anchor for certification path not found.

### ISSUE THREAD

**Issue by Seb3thehacker** [thrillfall/nextcloud-gpodder#74]
I'm running Nextcloud as snap using the built in self signed HTTPS certificate. ![Screenshot_20220524-143254_AntennaPod_1.png](https://user-images.githubusercontent.com/88462253/170136532-eccec988-a72f-418a-a0fd-187d09a54ccc.png)

**Comment by thrillfall** [comment]
This is the antennapod login screen, right? So this exception is thrown by antennapod. Please raise an  issue at their repo

**Comment by Seb3thehacker** [comment]
Yes. Will do

**Comment by maxlath** [comment]
for anyone looking for that issue on AntennaPod: https://github.com/AntennaPod/AntennaPod/issues/5911
