### ISSUE TITLE
Update 3.3.0 to 3.4.0 impossible

### ISSUE THREAD

**Issue by cr9christi9n** [thrillfall/nextcloud-gpodder#79]
Hi,
First, thanks for this wonderfull app !

My nextcloud is 24.0.1 under Debian 11.
Impossible to update GPodder from 3.3.0 to 3.4.0.
Update is visible in App menu with update button ... I click on it and update message disappear as it was updatted but no ... it appears again soon after !
Any help welcome ;o)
Cr9c

**Comment by cr9christi9n** [comment]
Hi @JonOfUs 
I update and reboot my system regularly .... so I just did it again ... same pb ... I just stop/restart PHP and APACHE ... same pb.
Rights on GpodderSync are the same than my others apps and till now (for at least 3 years, I never get any pb on it.

Regarding logs, wich one would you need ?

**Comment by JonOfUs** [comment]
The main Nextcloud log would be great.
You could lower your log level, open your log file with `tail -f nextcloud.log` (or however your log file is named) (tail -f constantly checks the given file for changes and prints new lines live into the terminal) and try to upgrade Nextcloud Gpodder once more. If any new log messages appear, these could immensely help to identify the problem.

**Comment by JonOfUs** [comment]
I fear this doesn't help me. These are the correct log entries, but all lines are cut off (the end is missing). I need the whole error messages, especially the specific part with "message: [...]".

**Comment by cr9christi9n** [comment]
Hi @JonOfUs 
Sorry for my last post wich has been cut !
Herewith whole "log" regarding GPodderSync update attempt today

`{"reqId":"xcJvv9KM0tP97hRtJPzF","level":3,"time":"2022-06-20T17:16:34+00:00","remoteAddr":"00.000.000.000","user":"user_name","app":"core","method":"GET","url":"/index.php/settings/apps/update/gpoddersync","message":"User backend OC_User_FTP not found.","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:101.0) Gecko/20100101 Firefox/101.0","version":"24.0.1.1"}
{"reqId":"xcJvv9KM0tP97hRtJPzF","level":3,"time":"2022-06-20T17:16:35+00:00","remoteAddr":"00.000.000.000","user":"user_name","app":"PHP","method":"GET","url":"/index.php/settings/apps/update/gpoddersync","message":"unlink(/var/www/nextcloud/apps/gpoddersync/appinfo/routes.php): Permission denied at /var/www/nextcloud/lib/private/legacy/OC_Helper.php#179","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:101.>
{"reqId":"xcJvv9KM0tP97hRtJPzF","level":3,"time":"2022-06-20T17:16:35+00:00","remoteAddr":"00.000.000.000","user":"user_name","app":"PHP","method":"GET","url":"/index.php/settings/apps/update/gpoddersync","message":"unlink(/var/www/nextcloud/apps/gpoddersync/appinfo/info.xml): Permission denied at /var/www/nextcloud/lib/private/legacy/OC_Helper.php#179","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:101.0)>
{"reqId":"xcJvv9KM0tP97hRtJPzF","level":3,"time":"2022-06-20T17:16:35+00:00","remoteAddr":"00.000.000.000","user":"user_name","app":"PHP","method":"GET","url":"/index.php/settings/apps/update/gpoddersync","message":"rmdir(/var/www/nextcloud/apps/gpoddersync/appinfo): Directory not empty at /var/www/nextcloud/lib/private/legacy/OC_Helper.php#177","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:101.0) Gecko/2>
{"reqId":"xcJvv9KM0tP97hRtJPzF","level":3,"time":"2022-06-20T17:16:35+00:00","remoteAddr":"00.000.000.000","user":"user_name","app":"PHP","method":"GET","url":"/index.php/settings/apps/update/gpoddersync","message":"unlink(/var/www/nextcloud/apps/gpoddersync/lib/Migration/Version0004Date20210823115513.php): Permission denied at /var/www/nextcloud/lib/private/legacy/OC_Helper.php#179","userAgent":"Mozilla/5.>
{"reqId":"xcJvv9KM0tP97hRtJPzF","level":3,"time":"2022-06-20T17:16:35+00:00","remoteAddr":"00.000.000.000","user":"user_name","app":"PHP","method":"GET","url":"/index.php/settings/apps/update/gpoddersync","message":"unlink(/var/www/nextcloud/apps/gpoddersync/lib/Migration/Version0002Date20210524131313.php): Permission denied at /var/www/nextcloud/lib/private/legacy/OC_Helper.php#179","userAgent":"Mozilla/5.>
{"reqId":"xcJvv9KM0tP97hRtJPzF","level":3,"time":"2022-06-20T17:16:35+00:00","remoteAddr":"00.000.000.000","user":"user_name","app":"PHP","method":"GET","url":"/index.php/settings/apps/update/gpoddersync","message":"unlink(/var/www/nextcloud/apps/gpoddersync/lib/Migration/TimestampMigration.php): Permission denied at /var/www/nextcloud/lib/private/legacy/OC_Helper.php#179","userAgent":"Mozilla/5.0 (X11; Lin>
{"reqId":"xcJvv9KM0tP97hRtJPzF","level":3,"time":"2022-06-20T17:16:35+00:00","remoteAddr":"00.000.000.000","user":"user_name","app":"PHP","method":"GET","url":"/index.php/settings/apps/update/gpoddersync","message":"unlink(/var/www/nextcloud/apps/gpoddersync/lib/Migration/Version0003Date20210822231113.php): Permission denied at /var/www/nextcloud/lib/private/legacy/OC_Helper.php#179","userAgent":"Mozilla/5.>
{"reqId":"xcJvv9KM0tP97hRtJPzF","level":3,"time":"2022-06-20T17:16:35+00:00","remoteAddr":"00.000.000.000","user":"user_name","app":"PHP","method":"GET","url":"/index.php/settings/apps/update/gpoddersync","message":"unlink(/var/www/nextcloud/apps/gpoddersync/lib/Migration/Version0005Date20211004110900.php): Permission denied at /var/www/nextcloud/lib/private/legacy/OC_Helper.php#179","userAgent":"Mozilla/5.>
{"reqId":"xcJvv9KM0tP97hRtJPzF","level":3,"time":"2022-06-20T17:16:35+00:00","remoteAddr":"00.000.000.000","user":"user_name","app":"PHP","method":"GET","url":"/index.php/settings/apps/update/gpoddersync","message":"unlink(/var/www/nextcloud/apps/gpoddersync/lib/Migration/Version0001Date20210520063113.php): Permission denied at /var/www/nextcloud/lib/private/legacy/OC_Helper.php#179","userAgent":"Mozilla/5.>
{"reqId":"xcJvv9KM0tP97hRtJPzF","level":3,"time":"2022-06-20T17:16:35+00:00","remoteAddr":"00.000.000.000","user":"user_name","app":"PHP","method":"GET","url":"/index.php/settings/apps/update/gpoddersync","message":"rmdir(/var/www/nextcloud/apps/gpoddersync/lib/Migration): Permission denied at /var/www/nextcloud/lib/private/legacy/OC_Helper.php#177","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:101.0) Gec>
{"reqId":"xcJvv9KM0tP97hRtJPzF","level":3,"time":"2022-06-20T17:16:35+00:00","remoteAddr":"00.000.000.000","user":"user_name","app":"PHP","method":"GET","url":"/index.php/settings/apps/update/gpoddersync","message":"unlink(/var/www/nextcloud/apps/gpoddersync/lib/Db/EpisodeAction/EpisodeActionWriter.php): Permission denied at /var/www/nextcloud/lib/private/legacy/OC_Helper.php#179","userAgent":"Mozilla/5.0 (>
{"reqId":"xcJvv9KM0tP97hRtJPzF","level":3,"time":"2022-06-20T17:16:35+00:00","remoteAddr":"00.000.000.000","user":"user_name","app":"PHP","method":"GET","url":"/index.php/settings/apps/update/gpoddersync","message":"unlink(/var/www/nextcloud/apps/gpoddersync/lib/Db/EpisodeAction/EpisodeActionRepository.php): Permission denied at /var/www/nextcloud/lib/private/legacy/OC_Helper.php#179","userAgent":"Mozilla/5>
{"reqId":"xcJvv9KM0tP97hRtJPzF","level":3,"time":"2022-06-20T17:16:35+00:00","remoteAddr":"00.000.000.000","user":"user_name","app":"PHP","method":"GET","url":"/index.php/settings/apps/update/gpoddersync","message":"unlink(/var/www/nextcloud/apps/gpoddersync/lib/Db/EpisodeAction/EpisodeActionMapper.php): Permission denied at /var/www/nextcloud/lib/private/legacy/OC_Helper.php#179","userAgent":"Mozilla/5.0 (>
{"reqId":"xcJvv9KM0tP97hRtJPzF","level":3,"time":"2022-06-20T17:16:35+00:00","remoteAddr":"00.000.000.000","user":"user_name","app":"PHP","method":"GET","url":"/index.php/settings/apps/update/gpoddersync","message":"unlink(/var/www/nextcloud/apps/gpoddersync/lib/Db/EpisodeAction/EpisodeActionEntity.php): Permission denied at /var/www/nextcloud/lib/private/legacy/OC_Helper.php#179","userAgent":"Mozilla/5.0 (>
{"reqId":"xcJvv9KM0tP97hRtJPzF","level":3,"time":"2022-06-20T17:16:35+00:00","remoteAddr":"00.000.000.000","user":"user_name","app":"PHP","method":"GET","url":"/index.php/settings/apps/update/gpoddersync","message":"rmdir(/var/www/nextcloud/apps/gpoddersync/lib/Db/EpisodeAction): Permission denied at /var/www/nextcloud/lib/private/legacy/OC_Helper.php#177","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:101>
{"reqId":"xcJvv9KM0tP97hRtJPzF","level":3,"time":"2022-06-20T17:16:35+00:00","remoteAddr":"00.000.000.000","user":"user_name","app":"PHP","method":"GET","url":"/index.php/settings/apps/update/gpoddersync","message":"unlink(/var/www/nextcloud/apps/gpoddersync/lib/Db/SubscriptionChange/SubscriptionChangeWriter.php): Permission denied at /var/www/nextcloud/lib/private/legacy/OC_Helper.php#179","userAgent":"Moz>
{"reqId":"xcJvv9KM0tP97hRtJPzF","level":3,"time":"2022-06-20T17:16:35+00:00","remoteAddr":"00.000.000.000","user":"user_name","app":"PHP","method":"GET","url":"/index.php/settings/apps/update/gpoddersync","message":"unlink(/var/www/nextcloud/apps/gpoddersync/lib/Db/SubscriptionChange/SubscriptionChangeRepository.php): Permission denied at /var/www/nextcloud/lib/private/legacy/OC_Helper.php#179","userAgent":>
{"reqId":"xcJvv9KM0tP97hRtJPzF","level":3,"time":"2022-06-20T17:16:35+00:00","remoteAddr":"00.000.000.000","user":"user_name","app":"PHP","method":"GET","url":"/index.php/settings/apps/update/gpoddersync","message":"unlink(/var/www/nextcloud/apps/gpoddersync/lib/Db/SubscriptionChange/SubscriptionChangeMapper.php): Permission denied at /var/www/nextcloud/lib/private/legacy/OC_Helper.php#179","userAgent":"Moz>
{"reqId":"xcJvv9KM0tP97hRtJPzF","level":3,"time":"2022-06-20T17:16:35+00:00","remoteAddr":"00.000.000.000","user":"user_name","app":"PHP","method":"GET","url":"/index.php/settings/apps/update/gpoddersync","message":"unlink(/var/www/nextcloud/apps/gpoddersync/lib/Db/SubscriptionChange/SubscriptionChangeEntity.php): Permission denied at /var/www/nextcloud/lib/private/legacy/OC_Helper.php#179","userAgent":"Moz>
{"reqId":"xcJvv9KM0tP97hRtJPzF","level":3,"time":"2022-06-20T17:16:35+00:00","remoteAddr":"00.000.000.000","user":"user_name","app":"PHP","method":"GET","url":"/index.php/settings/apps/update/gpoddersync","message":"rmdir(/var/www/nextcloud/apps/gpoddersync/lib/Db/SubscriptionChange): Permission denied at /var/www/nextcloud/lib/private/legacy/OC_Helper.php#177","userAgent":"Mozilla/5.0 (X11; Linux x86_64; r>
{"reqId":"xcJvv9KM0tP97hRtJPzF","level":3,"time":"2022-06-20T17:16:35+00:00","remoteAddr":"00.000.000.000","user":"user_name","app":"PHP","method":"GET","url":"/index.php/settings/apps/update/gpoddersync","message":"rmdir(/var/www/nextcloud/apps/gpoddersync/lib/Db): Permission denied at /var/www/nextcloud/lib/private/legacy/OC_Helper.php#177","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:101.0) Gecko/2010>
{"reqId":"xcJvv9KM0tP97hRtJPzF","level":3,"time":"2022-06-20T17:16:35+00:00","remoteAddr":"00.000.000.000","user":"user_name","app":"PHP","method":"GET","url":"/index.php/settings/apps/update/gpoddersync","message":"unlink(/var/www/nextcloud/apps/gpoddersync/lib/Core/EpisodeAction/EpisodeActionSaver.php): Permission denied at /var/www/nextcloud/lib/private/legacy/OC_Helper.php#179","userAgent":"Mozilla/5.0 >
{"reqId":"xcJvv9KM0tP97hRtJPzF","level":3,"time":"2022-06-20T17:16:35+00:00","remoteAddr":"00.000.000.000","user":"user_name","app":"PHP","method":"GET","url":"/index.php/settings/apps/update/gpoddersync","message":"unlink(/var/www/nextcloud/apps/gpoddersync/lib/Core/EpisodeAction/EpisodeAction.php): Permission denied at /var/www/nextcloud/lib/private/legacy/OC_Helper.php#179","userAgent":"Mozilla/5.0 (X11;>
{"reqId":"xcJvv9KM0tP97hRtJPzF","level":3,"time":"2022-06-20T17:16:35+00:00","remoteAddr":"00.000.000.000","user":"user_name","app":"PHP","method":"GET","url":"/index.php/settings/apps/update/gpoddersync","message":"unlink(/var/www/nextcloud/apps/gpoddersync/lib/Core/EpisodeAction/EpisodeActionReader.php): Permission denied at /var/www/nextcloud/lib/private/legacy/OC_Helper.php#179","userAgent":"Mozilla/5.0>
{"reqId":"xcJvv9KM0tP97hRtJPzF","level":3,"time":"2022-06-20T17:16:35+00:00","remoteAddr":"00.000.000.000","user":"user_name","app":"PHP","method":"GET","url":"/index.php/settings/apps/update/gpoddersync","message":"rmdir(/var/www/nextcloud/apps/gpoddersync/lib/Core/EpisodeAction): Permission denied at /var/www/nextcloud/lib/private/legacy/OC_Helper.php#177","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:1>
{"reqId":"xcJvv9KM0tP97hRtJPzF","level":3,"time":"2022-06-20T17:16:35+00:00","remoteAddr":"00.000.000.000","user":"user_name","app":"PHP","method":"GET","url":"/index.php/settings/apps/update/gpoddersync","message":"unlink(/var/www/nextcloud/apps/gpoddersync/lib/Core/SubscriptionChange/SubscriptionChangeSaver.php): Permission denied at /var/www/nextcloud/lib/private/legacy/OC_Helper.php#179","userAgent":"Mo>
{"reqId":"xcJvv9KM0tP97hRtJPzF","level":3,"time":"2022-06-20T17:16:35+00:00","remoteAddr":"00.000.000.000","user":"user_name","app":"PHP","method":"GET","url":"/index.php/settings/apps/update/gpoddersync","message":"unlink(/var/www/nextcloud/apps/gpoddersync/lib/Core/SubscriptionChange/SubscriptionChange.php): Permission denied at /var/www/nextcloud/lib/private/legacy/OC_Helper.php#179","userAgent":"Mozilla>
{"reqId":"xcJvv9KM0tP97hRtJPzF","level":3,"time":"2022-06-20T17:16:35+00:00","remoteAddr":"00.000.000.000","user":"user_name","app":"PHP","method":"GET","url":"/index.php/settings/apps/update/gpoddersync","message":"unlink(/var/www/nextcloud/apps/gpoddersync/lib/Core/SubscriptionChange/SubscriptionChangesReader.php): Permission denied at /var/www/nextcloud/lib/private/legacy/OC_Helper.php#179","userAgent":">
{"reqId":"xcJvv9KM0tP97hRtJPzF","level":3,"time":"2022-06-20T17:16:35+00:00","remoteAddr":"00.000.000.000","user":"user_name","app":"PHP","method":"GET","url":"/index.php/settings/apps/update/gpoddersync","message":"unlink(/var/www/nextcloud/apps/gpoddersync/lib/Core/SubscriptionChange/SubscriptionChangeRequestParser.php): Permission denied at /var/www/nextcloud/lib/private/legacy/OC_Helper.php#179","userAg>
{"reqId":"xcJvv9KM0tP97hRtJPzF","level":3,"time":"2022-06-20T17:16:35+00:00","remoteAddr":"00.000.000.000","user":"user_name","app":"PHP","method":"GET","url":"/index.php/settings/apps/update/gpoddersync","message":"rmdir(/var/www/nextcloud/apps/gpoddersync/lib/Core/SubscriptionChange): Permission denied at /var/www/nextcloud/lib/private/legacy/OC_Helper.php#177","userAgent":"Mozilla/5.0 (X11; Linux x86_64;>
{"reqId":"xcJvv9KM0tP97hRtJPzF","level":3,"time":"2022-06-20T17:16:35+00:00","remoteAddr":"00.000.000.000","user":"user_name","app":"PHP","method":"GET","url":"/index.php/settings/apps/update/gpoddersync","message":"rmdir(/var/www/nextcloud/apps/gpoddersync/lib/Core): Permission denied at /var/www/nextcloud/lib/private/legacy/OC_Helper.php#177","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:101.0) Gecko/20>
{"reqId":"xcJvv9KM0tP97hRtJPzF","level":3,"time":"2022-06-20T17:16:35+00:00","remoteAddr":"00.000.000.000","user":"user_name","app":"PHP","method":"GET","url":"/index.php/settings/apps/update/gpoddersync","message":"unlink(/var/www/nextcloud/apps/gpoddersync/lib/Controller/EpisodeActionController.php): Permission denied at /var/www/nextcloud/lib/private/legacy/OC_Helper.php#179","userAgent":"Mozilla/5.0 (X1>
{"reqId":"xcJvv9KM0tP97hRtJPzF","level":3,"time":"2022-06-20T17:16:35+00:00","remoteAddr":"00.000.000.000","user":"user_name","app":"PHP","method":"GET","url":"/index.php/settings/apps/update/gpoddersync","message":"unlink(/var/www/nextcloud/apps/gpoddersync/lib/Controller/SubscriptionChangeController.php): Permission denied at /var/www/nextcloud/lib/private/legacy/OC_Helper.php#179","userAgent":"Mozilla/5.>
{"reqId":"xcJvv9KM0tP97hRtJPzF","level":3,"time":"2022-06-20T17:16:35+00:00","remoteAddr":"00.000.000.000","user":"user_name","app":"PHP","method":"GET","url":"/index.php/settings/apps/update/gpoddersync","message":"rmdir(/var/www/nextcloud/apps/gpoddersync/lib/Controller): Permission denied at /var/www/nextcloud/lib/private/legacy/OC_Helper.php#177","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:101.0) Ge>
{"reqId":"xcJvv9KM0tP97hRtJPzF","level":3,"time":"2022-06-20T17:16:35+00:00","remoteAddr":"00.000.000.000","user":"user_name","app":"PHP","method":"GET","url":"/index.php/settings/apps/update/gpoddersync","message":"rmdir(/var/www/nextcloud/apps/gpoddersync/lib): Directory not empty at /var/www/nextcloud/lib/private/legacy/OC_Helper.php#177","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:101.0) Gecko/20100>
{"reqId":"xcJvv9KM0tP97hRtJPzF","level":3,"time":"2022-06-20T17:16:35+00:00","remoteAddr":"00.000.000.000","user":"user_name","app":"PHP","method":"GET","url":"/index.php/settings/apps/update/gpoddersync","message":"rmdir(/var/www/nextcloud/apps/gpoddersync): Directory not empty at /var/www/nextcloud/lib/private/legacy/OC_Helper.php#183","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:101.0) Gecko/20100101 >`

**Comment by JonOfUs** [comment]
I can't spot any gpoddersync problems here, so it is probably a problem of your instance's configuration.

It seems like there is a permissions problem. The Nextcloud user (probably `www-data`) is not allowed to delete the files in `/var/www/nextcloud/apps/gpoddersync/` and therefore the update cannot be done.

`"unlink(/var/www/nextcloud/apps/gpoddersync/appinfo/routes.php): Permission denied"`: `unlink()` is the php command to delete a file, so if this fails, php has not enough permissions to do that.

You may run a `ls -la /var/www/nextcloud/apps/gpoddersync` which will show you the permissions in your gpoddersync folder. If it does not return something like the following, you have to run some commands to fix your permissions and then retry updating.

Expected `ls` command output:
```text
drwxr-xr-x   4 www-data www-data 4096 May 4 00:00 .
drwxr-x---. 93 www-data www-data 4096 May 4 00:00 ..
drwxr-xr-x   2 www-data www-data 4096 May 4 00:00 appinfo
-rw-r--r--   1 www-data www-data 1927 May 4 00:00 CHANGELOG.md
drwxr-xr-x   6 www-data www-data 4096 May 4 00:00 lib
```
Especially the `drwxr-xr-x` and the `www-data www-data` are important.

Commands for fixing permissions:
```bash
chown -R www-data:www-data /var/www/nextcloud/apps/gpoddersync
find /var/www/nextcloud/apps/gpoddersync/ -type d -exec chmod 750 {} \;
find /var/www/nextcloud/apps/gpoddersync/ -type f -exec chmod 640 {} \;
```
This will fix all wrong permissions in your gpoddersync folder. (taken from [Nextcloud docs](https://docs.nextcloud.com/server/latest/admin_manual/maintenance/manual_upgrade.html))

Additionally, the first error is about external user backends, so if you have set up some custom user backends, it is possible that some faulty configurations there could also create problems (but I can't see how these should only affect updating apps, so these probably are additional problems). You should definitely check on that, so that `user_external` is installed and the `user_backend` array is correct in `config.php`.

**Comment by cr9christi9n** [comment]
Yes indeed, it was a matter of permissions !
But what is quite incomprehensible is I didn't make any intervention and changes of any kind "around" GpodderSync files !

Anyway, many thanks for your help and your app ;o)

**Comment by JonOfUs** [comment]
Happy to help. Odd that the permissions were incorrect, are the other apps' permissions correct? Maybe wrong because you installed the app manually.
