### ISSUE TITLE
Upgrade PHPUnit version

### ISSUE THREAD

**Issue by mattsches** [thrillfall/nextcloud-gpodder#8]
The [Nextcloud docs](https://docs.nextcloud.com/server/latest/developer_manual/core/unit-testing.html) say
> Nextcloud uses PHPUnit >= 4.8 for unit testing.

Right now, the current PHPUnit version is 9, and there have been some bigger changes with regard to class names/namespaces, e.g. `PHPUnit_Framework_TestCase` was replaced with `\PHPUnit\Framework\TestCase`. Also, the NC docs recommend extending from `\Test\TestCase` which in turn extends `\PHPUnit\Framework\TestCase`.

To make testing easier for more recent versions of NC, I would like to propose to use a more current version of PHPUnit for testing and to adapt the test cases accordingly.

**Comment by thrillfall** [comment]
Great idea! Do you feel like doing a PR for that? ;-)

**Comment by mattsches** [comment]
Not sure how to enforce a more recent version of PHPUnit, since it's not part of NC's `composer.json`, but it's installed separately.
But I could update the existing test files so that they work with PHPUnit 8.x/9.x … will prepare a PR later :)
