### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by Zocker1999NET** [thrillfall/nextcloud-gpodder#83]
Hey @thrillfall,

thanks for implementing this great app. I thought about helping to implement support for syncing to the Nextcloud Music app, and I might want to reuse (parts of) your code to implement that, depending on what makes sense (syncing the two databases of owncloud/music and this app or combining both to a single one a.k.a. implementing the API into the music app as well). However, your code is missing a license which makes it illegal to use your code without asking for permission before. So hereby I wanna ask you to add a license to this repository to make using/forking your code legal. If you don't know what license you want to use, you can either look into [this comparison set up by GitHub](https://choosealicense.com/licenses/) or just use the [AGPL 3.0 ](https://choosealicense.com/licenses/agpl-3.0/) used by many other OwnCloud/Nextcloud apps as well.

**Comment by thrillfall** [comment]
Thanks for pointing this out. AGPL sounds OK. @JonOfUs you have any thoughts on this one?

**Comment by JonOfUs** [comment]
Have not yet worked with licenses.
AGPLv3 sounds good to me, it sounds like a good idea to use the same license as most of the other apps (and Nextcloud server).

**Comment by thrillfall** [comment]
So how do we add this license?

**Comment by Zocker1999NET** [comment]
Copy the text of [AGPL](https://choosealicense.com/licenses/agpl-3.0/) into a new file called `LICENSE` and commit it. You may want to submit this as a PR and notify each past contributor so they all know as well.
